### ISSUE TITLE
Wordpress issue

### ISSUE THREAD

**Issue by eriktailor** [sonnyt/tweetie#13]
Hi there, i've been using tweetie in several times in html projects and i just love it and  never had a problem in the usuage. Now i'm trying to integrate it with wordpress with lack of success: I checked everything several times, but i always end up with the following error in the console:

<code>GET http://domain.com/api/tweet.php?username=&count=1&exclude_replies=false
 No input specified</code>

Any ideas what's wrong? Thanks!

**Comment by wickedst** [comment]
No reason why this can't work with WP. 

Here's what I did. I am using Bower, but you get the idea

`apiPath: '<?php echo get_stylesheet_directory_uri(); ?>/assets/js/vendor/Tweetie/api/tweet.php',`
