### ISSUE TITLE
"Loading..."

### ISSUE THREAD

**Issue by Doohi** [sonnyt/tweetie#36]
I keep getting "Loading..." rather than the actual feeds. Could you help me?

**Comment by The-Newt** [comment]
Hoping for some help with a similar issue and Ive hit rock bottom here.  I continue to also get the "Loading" display.  The api path is correct, as I can see it in a web browser, however, when I hit the tweet.php page,I get the following: You need a consumer key and secret keys. Get one from dev.twitter.com/apps.  I've got the keys loaded into this file!  I don't understand why it just will not work.  Any help would be greatly appreciated.  Thank you.
