### ISSUE TITLE
I m unable to see any data

### ISSUE THREAD

**Issue by suresh036** [sonnyt/tweetie#43]
Hi, 

I put the token and secret keys from the dev.twitter to the config file. However i am unable to see any data after that. Its just displaying "Loading... " and nothing else.

![capture](https://cloud.githubusercontent.com/assets/9982275/5222232/94bdc45e-76b5-11e4-92b5-df82e5a5d27b.JPG)

please guide me what i m doing wrong..

**Comment by ajaycr** [comment]
Hello,

I am trying to implement tweetie.js for an wordpress project. I did all that was needed. But I keep seeing 500 Internal Server Error on tweet.php. Could you please let me know how to solve the same

Thanks
