### ISSUE TITLE
Username and hashtag combined

### ISSUE THREAD

**Issue by fredrikjahr** [sonnyt/Tweetie#48]
Hi,
I'm trying to retrieve tweets from a specific user AND with specific tags by using:

    <script class="source" type="text/javascript">
        $('.example1 .tweet').twittie({
            username: 'myUser',
            hashtag: 'myHash',
            dateFormat: '%b. %d, %Y',
            template: '{{tweet}} <div class="date">{{date}}</div>',
            count: 1,
            loadingText: 'Loading!'
        });
    </script>

But I get tweets from the specific user AND / OR with the specific tag.

How can I change this?

**Comment by beedaan** [comment]
+1
