### ISSUE TITLE
list feature not working

### ISSUE THREAD

**Issue by flaknugget** [sonnyt/Tweetie#50]
The option to get a feed from a list doesn't seem to work. The feed simply grabs all tweets from the 'username', and the 'list' option seems to do nothing, even in the demo 'index.html' included in the GIT.

http://padamson.com/Tweetie-master/original.html

**Comment by sonnyt** [comment]
Hey,

I just checked your page, it seems like the `c-oo-l-e-s-t-nerds-i-know` list doesn't exist or set to be private. While `BanfieldAgency` list pull works properly. Can you make sure that slug you enter is correct?

Sonny,
