### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by jonorherrington** [sonnyt/Tweetie#53]
Hey -

So while I love the idea that this is able to be installed via bower, there is a problem. Since you have to edit config.php every time you upgrade to the newest version, that file gets overwritten. Unless you use something like bowercopy within npm or grunt, this bower module basically is rendered useless. Anyone else have any ideas to fix this problem?

**Comment by jonorherrington** [comment]
Why was this closed? Is this not still a problem?

**Comment by sonnyt** [comment]
@jonorherrington this plugin is not a good candidate for a bower package since it contains `.php` files. Tweetie is not fully a javascript package, it heavily relies on other languages to function properly.

**Comment by jonorherrington** [comment]
I realize that. Why is there a bower package for it then?

**Comment by sonnyt** [comment]
@jonorherrington it shouldn't be there, good catch :+1:
