### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by makshh** [sonnyt/Tweetie#54]
Hi,

Is it possible to change date to something like '49 minutes ago', '2 days ago'?

**Comment by BN83** [comment]
I don't think the code does this already, however it can be done with some modification.

First you need to get the time from your tweet rather than just the date, then format the date using something like Livestamp/Moments.

**Comment by richgcook** [comment]
+1

**Comment by doidd** [comment]
I think, you can use with http://timeago.yarp.com.
