### ISSUE TITLE
Wordpress Version?

### ISSUE THREAD

**Issue by Costellos** [sonnyt/Tweetie#55]
Is there a wordpress version of this yet? If not would you mind If i made one? I wouldn't sell it. Just want to make something easy to use for wordpress that I can easily install on all of my sites, and figured it would be good to release to the public.

**Comment by Costellos** [comment]
I have completed the widget and am planing on releasing it to the WP Directory. Please let me know if you have a problem with this.

Thanks,
Steven Costello
Costello Coding

**Comment by robwent** [comment]
Do you need any testers?

**Comment by Costellos** [comment]
Sure, Il put a git with it this weekend. and Il reply to this thread with the link. I have it working, and I have used it, but would be helpful to have another set of eyes. 

Thanks,
Steven Costello
Costello Coding

**Comment by robwent** [comment]
I just actually integrated it with advanced custom fields but would be happy to have a play around and test for you.
