### ISSUE TITLE
Working on local

### ISSUE THREAD

**Issue by nufrankz** [sonnyt/tweetie#62]
Hey!
I downloaded this snippet (thank you), and put it to work.

Well, everything's already set, jquery 2.2.0 from google's cdn, the oauth keys (copy/paste), correct paths and the div that will receive the data.

This is my syntax:

`$('.contenidotwitter').twittie({
            dateFormat: 'de %B del %Y.',
            template: '<div class="tweet">{{tweet}}</div><div class="fecha">{{date}}</div>',
        });`

Working on Firefox on local mode (Internet just to obtain the feed and jquery) but it doesn't work (just "Loading").

Even the index.html example doesn't get the data.

What I'm doing wrong? Thank you! :)

**Comment by gomessimon** [comment]
I am having the same problem. Is there any solution for it?

**Comment by nowag** [comment]
@nufrankz @gomessimon 
Is PHP correctly enabled or installed?

**Comment by gomessimon** [comment]
I have solved it, it was a file permission issue in the server.

Best,
Simon Gomes

**Comment by lspoor** [comment]
I'm also receiving this problem? Working locally using MAMP. Any ideas?

**Comment by gomessimon** [comment]
In the server check your **api** folder and files permission inside it. **api** folder shoulw have 0755 (rwxr-xr-x) file excess permission, as well as all folders inside it, and all the **.php** files inside the **api** folder and it's sub folder should have 0644 (-rw-r--r-) file excess permission. Try it hope it will work, it worked for me.

**Comment by lspoor** [comment]
Is this when you've uploaded it to a web server? I'm simply just working in a directory on my desktop atm using Mamp as a local server

**Comment by gomessimon** [comment]
I user XAMPP in windows, not sure about MAMP, still check the file permissions. Possible you please share any error log? What exactly is the error message?

**Comment by lspoor** [comment]
I've got it partially working now, but another issue - https://github.com/sonnyt/Tweetie/issues/74

**Comment by amigoow** [comment]
In addition to file permissions it requires PHP Curl enabled.

To enable that go to php.ini file and remove ; from this line:
`;extension=php_curl.dll
`
