### ISSUE TITLE
Nothing shows

### ISSUE THREAD

**Issue by rjpedrosa** [sonnyt/Tweetie#63]
Hi,

I am trying to implement this on a wordpress website.

I have this init code on the document.ready():

`$('#twitter-feed').twittie({
        username: 'interel_global',
        dateFormat: '%b. %d, %Y',
        template: '<strong class="date">{{date}}</strong> - {{screen_name}} {{tweet}}',
        count: 10,
	apiPath:'/wp-content/themes/interelbe/js/tweetie/api/tweet.php'
});`

And the WP include:

`wp_enqueue_script('tweetie',  get_template_directory_uri().'/js/tweetie/tweetie.min.js', array('jquery'), null, true);`

And the target div: 
`<div id="twitter-feed"></div>`

And nothing displays on the div. If I remove the "apiPath" parameter, it only shows "Loading..." (and get a 404 on the console, for not finding the tweet.php file).

Any help? Thanks!

**Comment by sonnyt** [comment]
This plugin is not meant to work with Wordpress.

**Comment by frankyinternets** [comment]
If this plugin is not meant to work with Wordpress can you put it very clearly in the Readme??? Or can you work with the number of folks that have offered to help make that possible... Or post other's solution as a link in the Readme... It's the plugin that comes up in most searches for a Js plugin you could do folks a big service by warding them off early.
