### ISSUE TITLE
Only one item loaded

### ISSUE THREAD

**Issue by BeatLaG** [sonnyt/Tweetie#69]
Hello,

I´m having a very weird issue. Everything worked well until today where I realized that the plugin only generates one tweet. Does not mind how many items I pass to the plugin, it always returns one. The weirdest thing is that if I set a '5' value, the plugin generates 2 tweets.

Could you please give some fresh air about this?

Thanks!

**Comment by BeatLaG** [comment]
`$('.twitter-feed').twittie({
			            dateFormat: '%b. %d, %Y',
			            template: '<div class="carousel-caption"><div class="twt-meta"><div class="date">{{date}}&nbsp;&mdash;</div><div class="twt-id">&nbsp;{{screen_name}}</div></div>{{tweet}}</div>',
			            count: twtCount,
			            hideReplies: true
			        }, function() {
					    $(".twitter-feed").find(".item").first().addClass("active");
					    $(".twitter-feed > ul > .item").appendTo(".twitter-feed");
					    $(".twitter-feed > ul").remove();
					});`

This is the way I´m loading the data.

**Comment by randomobject** [comment]
Having same issue. Any luck with a fix?

**Comment by randomobject** [comment]
.. after a week of no-luck, the website reverted back to having the correct amount of tweets. I have a vague feeling there's an issue with retweeting. Going to narrow this down when I can, and update here.

**Comment by sonnyt** [comment]
@BeatLaG @randomobject Do you have retweets off? I believe it's because Twitter API is returning 5 tweets and then filtering out all the retweets, leaving you with 2 in total. 😞

**Comment by sonnyt** [comment]
@BeatLaG @randomobject This is from Twitter's API doc.

> This parameter will prevent replies from appearing in the returned timeline. Using exclude_replies with the count parameter will mean you will receive up-to count tweets — this is because the count parameter retrieves that many tweets before filtering out retweets and replies. This parameter is only supported for JSON and XML responses.
