### ISSUE TITLE
Lists not working

### ISSUE THREAD

**Issue by rjpedrosa** [sonnyt/Tweetie#71]
Hi,

Loading lists doesn't seem to be working.
Using "/tweetie/api/tweet.php?username=TWITTER_ACCOUNT&list=LIST&count=5&exclude_replies=true"

Any help?

Thanks

**Comment by StrikerEureka7** [comment]
I believe the error is at line 16 of api/tweet.php file.
The second parameter of the filter_input() function should be 'list' (instead of 'list_slug') .
`$list_slug = filter_input(INPUT_GET, 'list', FILTER_SANITIZE_SPECIAL_CHARS);`

**Comment by rjpedrosa** [comment]
Yes, it works.
I'll do a pull request.

Thanks

**Comment by sonnyt** [comment]
Pull request merged, thank you @rjpedrosa !
