### ISSUE TITLE
No tweets showing but LI's created?

### ISSUE THREAD

**Issue by lspoor** [sonnyt/tweetie#74]
Followed as per the instructions, inserted my keys and using the following code to initiate it all but I just get an empty list being output..whats going on here?

`<script type="text/javascript">
        $('.tweet').twittie({
            dateFormat: '%b. %d, %Y',
            template: '{{tweet}} <div class="date">{{date}}</div>',
            count: 5,
            username: 'lukespoor',
            loadingText: 'Loading!'
        });
    </script>`

This is what is output:

`<div class="tweet">
    <ul>
        <li>
            <div class="date"></div>
        </li>
        <li>
            <div class="date"></div>
        </li>
        <li>
            <div class="date"></div>
        </li>
        <li>
            <div class="date"></div>
        </li>
        <li>
            <div class="date"></div>
        </li>
    </ul>
</div>`

**Comment by gomessimon** [comment]
Is there any error in the console log.

**Comment by lspoor** [comment]
Nothing is showing in the console buddy. Seems to be all fine but the <li>'s are empty

**Comment by sonnyt** [comment]
Hey @lspoor, do you have a link I can check out?

**Comment by lspoor** [comment]
Hey @sonnyt I don't have any hosting or anything at the moment I'm afraid, is there any way you could help? Perhaps skype/screen share? Let me know buddy

**Comment by gomessimon** [comment]
@lspoor buddy, share it using any cloud code sharing service like [Codeanywhere](https://codeanywhere.com/)  or [Plunker](https://plnkr.co/) or maybe **github**

**Comment by lspoor** [comment]
Its a full site which I can't really be sharing at the moment, as said I did was use the code from the demo, just adding in my keys

**Comment by gomessimon** [comment]
It is hard to tell without debugging bro, no clue.
