### ISSUE TITLE
Show only loading and nothing. 

### ISSUE THREAD

**Issue by Shmasya** [sonnyt/Tweetie#75]
With start page this plugin Show only loading and nothing.  Console error not have.

**Comment by davidwashburn** [comment]
Same issue for me. I have input my Keys from Twitter and nothing. I don't have a callback URL set on Twitter (since Im uncertain what that is/does) so that may be an issue. I'm not sure.

**Comment by davidwashburn** [comment]
The website I am running this on is:

https://brotherhoodgaming.net/tweetie/index.php

**Comment by amigoow** [comment]
@Shmasya @davidwashburn  Please see this issue. Hope it will help:

https://github.com/sonnyt/Tweetie/issues/62
