### ISSUE TITLE
How to add feature like "2 days ago" per tweet.

### ISSUE THREAD

**Issue by MoradHamdy** [sonnyt/tweetie#89]
@sonnyt 

Hello there,

I didn't find this feature available in the "Date Format" formula to show since how much time a single tweet is made, like '2 days ago', '27 minutes ago' or '30 seconds ago'.

Also including the template feature like {{tweeted_since}}.

If someone can provide a change for that, then it will be much appreciated!

**Comment by keverett** [comment]
Change relative_time(tweet.created_at) and add function below.

function relative_time(time_value) {
  var values = time_value.split(" ");
  time_value = values[1] + " " + values[2] + ", " + values[5] + " " + values[3];
  var parsed_date = Date.parse(time_value);
  var relative_to = (arguments.length > 1) ? arguments[1] : new Date();
  var delta = parseInt((relative_to.getTime() - parsed_date) / 1000);
  delta = delta + (relative_to.getTimezoneOffset() * 60);
 
  var r = '';
  if (delta < 60) {
        r = 'a minute ago';
  } else if(delta < 120) {
        r = 'couple of minutes ago';
  } else if(delta < (45*60)) {
        r = (parseInt(delta / 60)).toString() + ' minutes ago';
  } else if(delta < (90*60)) {
        r = 'an hour ago';
  } else if(delta < (24*60*60)) {
        r = '' + (parseInt(delta / 3600)).toString() + ' hours ago';
  } else if(delta < (48*60*60)) {
        r = '1 day ago';
  } else {
        r = (parseInt(delta / 86400)).toString() + ' days ago';
  }
 
      return r;
  }

**Comment by MoradHamdy** [comment]
@keverett 

I have added your function in the end of the plugin file. What to do then?

I also want to include the template feature like {{tweeted_since}}.

**Comment by keverett** [comment]
@MoradHamdy Inside the plugin file (tweetie.js) change tweet.created_at to relative_time(tweet.created_at)

Create a  new variable the same as .create_at and only use the function for that variable.  {{tweeted_since}}
